---
title: "Bootstrapping"
output: github_document
---
this is the repository for bootstrapping of P8105

```{r setup}
library(tidyverse)
library(modelr)
library(p8105.datasets)

set.seed(1)

```

do some bootstrapping
make up some data
```{r}
n_samp = 250

sim_df_constant = 
  tibble(
    x=rnorm(n_samp, 1,1),
    error=rnorm(n_samp, 0,1),
    y=2+3*x+error
  )

sim_df_nonconstant = sim_df_constant |> 
  mutate(
  error = error * .75 * x,
  y = 2 + 3 * x + error
)
```

lets look at these
```{r}
sim_df = 
  bind_rows(const = sim_df_constant, nonconstant = sim_df_nonconstant, .id = "data_source") 

sim_df |> 
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = .5) +
  stat_smooth(method = "lm") +
  facet_grid(~data_source) 
```

Look at regression results
```{r}
lm(y ~ x, data = sim_df_constant) |> 
  broom::tidy() |> 
  knitr::kable(digits = 3)
```

## Draw a bootstrap sample
```{r}
boot_sample = function(df){
  
  boot_df =
    sample_frac(df, replace=TRUE) |>
    arrange(x)
  
  return(boot_df)
}
```

lets try running this
```{r}
sim_df_nonconstant |>
  boot_sample() |>
  ggplot(aes (x=x, y=y)) +
  geom_point(alpha=0.05)+
  stat_smooth(method = "lm")
```

can we do this part of an analysis?
```{r}
sim_df_nonconstant |>
  boot_sample() |>
  lm(y~x, data = _)|>
  broom::tidy()|>
  knitr::kable(digits =3)
```

## Boostrap a lot
```{r}
boot_straps = 
  tibble(
    strap_number = 1:1000,
    ) |> 
  mutate(
    strap_sample = map(strap_number, \(i) boot_sample(df = sim_df_nonconstant)),
    models = map(strap_sample, \(strap_df) lm(y~x, data=strap_df)),
    results = map(models, broom::tidy)
  )

boot_results =
  boot_straps |>
  select(strap_number, results) |>
  unnest(results)|>
  group_by(term) |>
  summarize(
    boot_se = sd(estimate)
  )
```

## Using modelr
```{r}
boot_straps =
  sim_df_nonconstant |>
  modelr::bootstrap(1000) |>
  mutate(
    strap = map(strap, as_tibble),
    models = map(strap, \(df) lm(y~x, data=df)),
    results = map(models, broom::tidy)
  ) |>
  select(.id, results)|>
  unnest(results)
```

```{r}
boot_straps |> 
  group_by(term) |> 
  summarize(
    ci_lower = quantile(estimate, 0.025), 
    ci_upper = quantile(estimate, 0.975))
```

## Airbnb
```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Manhattan") |> 
  drop_na(price, stars) |> 
  select(price, stars, borough, neighborhood, room_type)
```

```{r}
nyc_airbnb |> 
  ggplot(aes(x = stars, y = price, color = room_type)) + 
  geom_point() 
```


